{% set name = "geomet" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0020a4426469934fb58f541cdc23f27c0c0fbbb3d003ee2cb76bb7ffa96a7506

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geomet = geomet.tool:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - click

test:
  imports:
    - geomet
  commands:
    - geomet -h

about:
  home: https://github.com/geomet/geomet
  license: Apache-2.0
  license_file: LICENSE
  summary: GeoMet - Convert GeoJSON to WKT/WKB, and vice versa
  description: |
    Convert GeoJSON to WKT/WKB (Well-Known Text/Binary) or GeoPackage Binary,
    and vice versa. Extended WKB/WKT are also supported.
    Conversion functions are exposed through idiomatic load/loads/dump/dumps
    interfaces.
    The name "GeoMet" was inspired by "met", the German word for mead.
    It is also a shortened version of the word "geometry".
    GeoMet is intended to cover all common use cases for dealing with 2D,
    3D, and 4D geometries (including 'Z', 'M', and 'ZM').
  dev_url: https://github.com/geomet/geomet

extra:
  recipe-maintainers:
    - avalentino
